workload:
  name: mistral-7b-4gpu-fsdp
  data:
    path: /pscratch/sd/k/kg597/c4_dataset/en
    seq_len: 512
    batch_size: 1
    max_docs: 128

hf_url: /pscratch/sd/k/kg597/llms/mistral-7b-instruct-v0.2

phase: training

Model-executor:
  model_plan_parallelization:
    dp_replicate: 1
    dp_shard: 4
    tp: 1
    pp: 1
