workload:
  name: qwen-8b-4gpu-tp
  data:
    path: /pscratch/sd/k/kg597/c4_dataset/en
    seq_len: 512
    batch_size: 1
    max_docs: 128

hf_url: /pscratch/sd/k/kg597/llms/Qwen2.5-7B-Instruct

phase: training

Model-executor:
  model_plan_parallelization:
    dp_replicate: 1
    dp_shard: 1
    tp: 4
    pp: 1
